### ISSUE TITLE
No errors but gist is not being updated.

### ISSUE THREAD

**Issue by chopfitzroy** [dfrankland/hyper-sync-settings#10]
No issues or output but when I try and: `Plugins > Sync Settings > Backup Settings` nothing happens the gist.

Running Ubuntu 16.04.

Cheers,
Otis.

**Comment by chopfitzroy** [comment]
Update:

Using devtools getting:

```

      (
      () => {
        const notification = new Notification(
          'hyperterm-sync-settings error 🔥',
          {
            body: 'TypeError: Cannot read property 'fetchAll' of undefined',
          }
        );
        undefined
      }
    )();
```

**Comment by chopfitzroy** [comment]
Update 2:

`Update`, `Backup`, and `Restore` all throw the same error.

`Repo`, has the correct repo in it with a `.git` and `.hyperterm.js` in it.

`Gist` Gist opens the correct gist in my browser.

`Configuration` opens the correct JSON file:

``` json
{
    "personalAccessToken": "***********************",
    "gistId": "7c522796738525b1e16b576ad25ef2e5"
}
```

**Comment by dfrankland** [comment]
I have yet to try this on Ubuntu. You may have to give me a bit more time to get setup and investigate what the issue is 👍

**Comment by chopfitzroy** [comment]
Hey @dfrankland,

That's all good I have found a temporary solution using symlinks to back up my `.hyperterm.js` with my dotfiles so no rush :).

Cheers.

**Comment by dfrankland** [comment]
So I found the main issue with this, I believe. It seems that [`nodegit`](https://github.com/nodegit/nodegit) absolutely will not install without being root user. **This may seriously mess up your permissions, so take caution following these steps on your actual machine!** My steps to install this plugin are as follow:
1. Use the Ubuntu 16.04 image from [osboxes.org](http://www.osboxes.org/ubuntu/) in VirtualBox
2. Install `node` using the recommended method via a package manager:
   
   ``` bash
   curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
   sudo apt-get install -y nodejs
   ```
3. Install HyperTerm using [this script](https://gist.github.com/dfrankland/fa7a4218113dd6de6931c2e1907df82d):
   
   ``` bash
   curl -sL https://gist.githubusercontent.com/dfrankland/fa7a4218113dd6de6931c2e1907df82d/raw/5d0611c73657ff22fe33365e704fcd97c3b50516/install-hyperterm.sh | sudo -E bash -
   ```
4. Open HyperTerm so that it creates default configuration files
5. Edit `~/.hyperterm.js` and add `'hyperterm-sync-settings'` to `plugins: []`
6. Close all HyperTerm windows
7. Open HyperTerm as root (HyperTerm may throw some errors, ignore them):
   
   ``` bash
   sudo HyperTerm
   ```
8. Try to install plugins by clicking `Plugins > Update All Now`
9. Wait for plugins to install
10. Close all HyperTerm windows
11. Open HyperTerm like normal and everything should work!

Sorry that this is a non-optimal process. [`nodegit` has lots of issues...](https://github.com/nodegit/nodegit/issues) but it is the most supported `git` bindings library for `node`.

**Comment by chopfitzroy** [comment]
Hey @dfrankland,

Thanks for getting onto that so quickly I will test out on my local machine over the weekend :).

Cheers.

**Comment by dfrankland** [comment]
If you have any more issues, please feel free to create another issue. There will be another release soon so it'll be great to get an update.
