### ISSUE TITLE
Fresh install fails to load "Cannot find module babel-runtime/helpers/toConsumableArray"

### ISSUE THREAD

**Issue by amrtgaber** [dfrankland/hyper-sync-settings#24]
Hello,

Hyper Term version: 1.2.1
node version: 6.10.0
npm version: 3.10.10
I'm using nvm.

Just added hyper-sync-settings to the plugins in the `.hyper.js` file. For what it's worth, the only other plugins I have installed are hyperline and hypercwd.

I installed babel-runtime globally via `npm install -g babel-runtime` but no dice.

Let me know if there's any other info I can add to help.
Amr

**Comment by dfrankland** [comment]
What OS are you running and what version of `hyper-sync-settings` have you got?

**Comment by amrtgaber** [comment]
@dfrankland My OS is a corporate custom version of ubuntu and the `hyper-sync-settings` version that get's installed is 2.0.1 (which I grabbed from `.hyper_plugins/node_modules/hyper-sync-settings/package.json`).

Hope that helps!
Amr

**Comment by victorloux** [comment]
I had the same problem on macOS. With latest versions of Hyper (1.2.1) and hyper-sync-settings (2.0.1); Node 7.6.0, and npm 4.1.2, installed via Homebrew.

Managed to solve it by doing `npm install babel-runtime` **from inside** the `~/.hyper_plugins` folder (rather than globally, as @amrtgaber tried), then restarting Hyper. It's now working fine 👍 

My guess is that the latest version/refactor 3e10bf80cbc07d057ad317549ec855e216502f00  caused this — `babel-runtime` is included in the devDependencies (as a subdependency of babel-cli) so it worked for you @dfrankland, but it isn't in the general dependencies in package.json for the rest of us.

**Comment by amrtgaber** [comment]
@victorloux Thanks that worked like a charm. Once `babel-runtime` was installed in `~/.hyper_plugins/node_modules` it launched just fine. Thanks!

**Comment by amrtgaber** [comment]
I did notice that the `babel-runtime` module disappears from time to time so I ended up running `npm install --save babel-runtime` in the `~/.hyper_plugins` folder which added it to the hyper plugins `package.json`. I doubt this is a desirable long term solution but it's an effective workaround.
