### ISSUE TITLE
Error updating plugins

### ISSUE THREAD

**Issue by aeimer** [dfrankland/hyper-sync-settings#34]
Hi there, I run
- Hyper 2.0.0
- Win10 x64
- Hyper-Sync-Settings 2.0.2

On starting Hyper, one minute later I get the following Message:

![grafik](https://user-images.githubusercontent.com/25035182/39622335-0f46596c-4f92-11e8-96cf-70107bbd7bfe.png)

How does this come? I couldn't find any npm/yarn logs with more info...

**Comment by sxhexe** [comment]
I have the same problem. Have you found a solution?

**Comment by rfgamaral** [comment]
Having the same problem. Thought it was a bad configuration on my side, but I guess it's not!?

**Comment by aeimer** [comment]
I couldn't find a way to get rid of this error. I also experienced that the git pull does not work. When I pull the gist manually the updating works over the gui

**Comment by rfgamaral** [comment]
> When I pull the gist manually the updating works over the gui

Can you please clarify this?

**Comment by aeimer** [comment]
@rfgamaral i think this is another issue, but when I click on restore settings it does not work. I first have to go via shell to the .hyper_settings/.hyper_restire_gist/ folder and run a git pull. Then I can run the restore settings again, this time the settings getting updated

**Comment by rfgamaral** [comment]
Ok, thanks. In my case, I can't backup or restore, it's simply not working for me. I always get the error you originally posted.

**Comment by aeimer** [comment]
Backuping works for me fine

**Comment by rfgamaral** [comment]
Just opened a pull request to fix this issue, it removes Electron as dependency which is not actually required (check PR).

In the mean time, to work around the issue, you can clone [rfgamaral/hyper-sync-settings](https://github.com/rfgamaral/hyper-sync-settings) to your `.hyper_plugins/local` folder and switch to the `fix/remove-electron-dependency` branch.

Don't forget to call `yarn install` / `npm install` to generate a build, otherwise the plugin won't load.

**Comment by rfgamaral** [comment]
Instead of all the trouble above, you can now just add `hyper-sync-settings#rfgamaral/hyper-sync-settings` to `.hyper.js` plugins section to use my fix until #35 is merged and a new release is published.

**Disclaimer:** It will also include other fixes/features because it pulls directly from my clone's `master` branch (at the time of writing it also includes #36). If you just want the fix for this issue, add `hyper-sync-settings#rfgamaral/hyper-sync-settings#bc59180a6f9da0ee2db89cb9a47e437a4e0e3743` instead.
