### ISSUE TITLE
"Settings not found" using ENV vars

### ISSUE THREAD

**Issue by benadamstyles** [dfrankland/hyper-sync-settings#6]
Hi, I'm getting the `Settings not found!` error. I have the (secret) gist set up, and a personal access token with `gist` scope. I save these to ENV vars, and confirmed that they are available to the shell:

```
echo $HYPERTERM_SYNC_SETTINGS_GIST_ID
<returns the id>
echo $HYPERTERM_SYNC_SETTINGS_PERSONAL_ACCESS_TOKEN
<returns the token>
```

Not sure what to try next? I have tried closing down HyperTerm and reopening. Thanks for any help you can give!

**Comment by dfrankland** [comment]
The real issue I believe you may be having is setting those environmental variables **_before_** your HyperTerm shell starts. By setting them in any `.bashrc`/`.bash_profile`/`config.fish` etc. HyperTerm executes those scripts **_after_** starting, so `hyperterm-sync-settings` has no way of reading those variables.

I recommend to just save these settings to `~/.hyperterm_plugins/.hyperterm-sync-settings.json`, as outlined in [the setup instructions](https://github.com/dfrankland/hyperterm-sync-settings#setup).

Otherwise, you'll need to create another script that sets those environmental variables before opening HyperTerm. For example:

``` bash
HYPERTERM_SYNC_SETTINGS_GIST_ID='787698769sdfs9d87f6' \
HYPERTERM_SYNC_SETTINGS_PERSONAL_ACCESS_TOKEN='9sd87f0s87df08sd7f' \
open /Applications/HyperTerm.app
```

**Comment by benadamstyles** [comment]
Ah, if I open HyperTerm from another terminal using `open /Applications/HyperTerm.app`, `hyperterm-sync-settings` works great! So yes, it must be that my `.zshrc` is executed after HyperTerm initialises its plugins, unless it is opened from a shell where the env vars are already available. Going to close this. Thanks for your help again.
